/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tudoapp.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Projeto;
import model.Tarefa;
import tudoapp.controler.ProjetoControler;
import tudoapp.controler.TarefaControler;
import util.ButtonColumnCellRederer;
import util.DeadlineColumnRed;
import util.TarefaTableModel;

/**
 *
 * @author PC
 */
public class MainScreen extends javax.swing.JFrame {
        
    ProjetoControler projectControler;
    TarefaControler tarefaControler;
    
    DefaultListModel projectModel;
    TarefaTableModel tarefaModel;
    
        

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        
        initDataControler();
        initComponetsModel();
        decorateTableTask();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelTolbar = new javax.swing.JPanel();
        jLabelTolbarTitle = new javax.swing.JLabel();
        jLabelTolbarsubTitle = new javax.swing.JLabel();
        jPanelProjects = new javax.swing.JPanel();
        jLabelProjectsTitle = new javax.swing.JLabel();
        jLabelProjectsAdd = new javax.swing.JLabel();
        jPanelTasks = new javax.swing.JPanel();
        jLabelTaskstitle = new javax.swing.JLabel();
        jLabelTasksAdd = new javax.swing.JLabel();
        jPanelProjectList = new javax.swing.JPanel();
        jScrollPaneProjects = new javax.swing.JScrollPane();
        jListProjects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTask = new javax.swing.JTable();
        jPanelEmptList = new javax.swing.JPanel();
        jLabelEmptListIcon = new javax.swing.JLabel();
        jLabelEmptListTitle = new javax.swing.JLabel();
        jLabelEmptListSubtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));

        jPainelTolbar.setBackground(new java.awt.Color(0, 204, 102));

        jLabelTolbarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTolbarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTolbarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudoapp/view/resources/tick.png"))); // NOI18N
        jLabelTolbarTitle.setText(" Tudo App");

        jLabelTolbarsubTitle.setText("Anote tudo não esqueça de nada");

        javax.swing.GroupLayout jPainelTolbarLayout = new javax.swing.GroupLayout(jPainelTolbar);
        jPainelTolbar.setLayout(jPainelTolbarLayout);
        jPainelTolbarLayout.setHorizontalGroup(
            jPainelTolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelTolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelTolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTolbarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTolbarsubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPainelTolbarLayout.setVerticalGroup(
            jPainelTolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelTolbarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTolbarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTolbarsubTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProjects.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjectsTitle.setForeground(new java.awt.Color(0, 204, 102));
        jLabelProjectsTitle.setText("Projetos");

        jLabelProjectsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudoapp/view/resources/add.png"))); // NOI18N
        jLabelProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProjectsLayout = new javax.swing.GroupLayout(jPanelProjects);
        jPanelProjects.setLayout(jPanelProjectsLayout);
        jPanelProjectsLayout.setHorizontalGroup(
            jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabelProjectsAdd)
                .addContainerGap())
        );
        jPanelProjectsLayout.setVerticalGroup(
            jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelProjectsLayout.createSequentialGroup()
                        .addComponent(jLabelProjectsAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(jLabelProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelTasks.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTaskstitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTaskstitle.setForeground(new java.awt.Color(0, 204, 102));
        jLabelTaskstitle.setText("Tarefas");

        jLabelTasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudoapp/view/resources/add.png"))); // NOI18N
        jLabelTasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
        jPanelTasks.setLayout(jPanelTasksLayout);
        jPanelTasksLayout.setHorizontalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTaskstitle, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTasksAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelTasksLayout.setVerticalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTaskstitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTasksAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelProjectList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jListProjects.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jListProjects.setFixedCellHeight(50);
        jListProjects.setSelectionBackground(new java.awt.Color(0, 204, 102));
        jListProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjectsMouseClicked(evt);
            }
        });
        jScrollPaneProjects.setViewportView(jListProjects);

        javax.swing.GroupLayout jPanelProjectListLayout = new javax.swing.GroupLayout(jPanelProjectList);
        jPanelProjectList.setLayout(jPanelProjectListLayout);
        jPanelProjectListLayout.setHorizontalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProjectListLayout.setVerticalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTableTask.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTask.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTask.setRowHeight(50);
        jTableTask.setSelectionBackground(new java.awt.Color(0, 204, 102));
        jTableTask.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTask.setShowVerticalLines(false);
        jTableTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTaskMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTask);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelEmptList.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEmptListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudoapp/view/resources/lists.png"))); // NOI18N
        jLabelEmptListIcon.setText("jLabel7");

        jLabelEmptListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmptListTitle.setForeground(new java.awt.Color(0, 204, 102));
        jLabelEmptListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptListTitle.setText("Nenhuma Tarefa Por aqui :D");

        jLabelEmptListSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelEmptListSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptListSubtitle.setText("Clique no botão '+' para adicionar uma nova Tarefa");

        javax.swing.GroupLayout jPanelEmptListLayout = new javax.swing.GroupLayout(jPanelEmptList);
        jPanelEmptList.setLayout(jPanelEmptListLayout);
        jPanelEmptListLayout.setHorizontalGroup(
            jPanelEmptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmptListLayout.createSequentialGroup()
                .addGroup(jPanelEmptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEmptListSubtitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmptListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmptListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEmptListLayout.setVerticalGroup(
            jPanelEmptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptListLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelEmptListIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmptListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmptListSubtitle)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelEmptList, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainelTolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPainelTolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjectsAddMouseClicked
        // TODO add your handling code here: evento que acontece ao clicar no botão
        //ciação do evento clickmouse
        ProjectDiologScreen projectDialogScreen = new ProjectDiologScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        //esse trecho de código realiza a atualização dos projetos quando a janela é fechada
        //assim que o projeto for criado ele será carregado na lista de projeto no mainScreen
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e){
                loadProjects();
            }
});
        
        
        
    }//GEN-LAST:event_jLabelProjectsAddMouseClicked

    private void jLabelTasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTasksAddMouseClicked
        // TODO add your handling code here:
        TaksDialogScreen taskDialogScreen = new TaksDialogScreen(this, rootPaneCheckingEnabled);
        //taskDialogScreen.setProjeto(null);
        
        //retorna o indice do projeto selecionado
        int projectIndex = jListProjects.getSelectedIndex();
        Projeto projeto = (Projeto) projectModel.get(projectIndex);
        taskDialogScreen.setProjeto(projeto);
        
        taskDialogScreen.setVisible(true);
        
        taskDialogScreen.addWindowListener(new WindowAdapter() {
             public void windowClosed(WindowEvent e){
                 
                int projectIndex = jListProjects.getSelectedIndex();
                Projeto projeto = (Projeto) projectModel.get(projectIndex);
                 loadTasks(projeto.getId());
            }
});
        
        
        
    }//GEN-LAST:event_jLabelTasksAddMouseClicked

    private void jTableTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTaskMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTableTask.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTask.columnAtPoint(evt.getPoint());
        Tarefa tarefa = tarefaModel.getTarefas().get(rowIndex);
        
        switch(columnIndex){
             
          case 3:
              
              tarefaControler.update(tarefa);
              break;
            
            case 4:
              break;
            
            case 5:
                
                tarefaControler.removebyid(tarefa.getId());
                tarefaModel.getTarefas().remove(tarefa);
                int projectIndex = jListProjects.getSelectedIndex();
                Projeto projeto = (Projeto) projectModel.get(projectIndex);
                loadTasks(projeto.getId());
                        
                        
              break;
              
        }
    }//GEN-LAST:event_jTableTaskMouseClicked

    private void jListProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjectsMouseClicked
        // TODO add your handling code here:
        int projectIndex = jListProjects.getSelectedIndex();
        Projeto projeto = (Projeto) projectModel.get(projectIndex);
        loadTasks(projeto.getId());
        
    }//GEN-LAST:event_jListProjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEmptListIcon;
    private javax.swing.JLabel jLabelEmptListSubtitle;
    private javax.swing.JLabel jLabelEmptListTitle;
    private javax.swing.JLabel jLabelProjectsAdd;
    private javax.swing.JLabel jLabelProjectsTitle;
    private javax.swing.JLabel jLabelTasksAdd;
    private javax.swing.JLabel jLabelTaskstitle;
    private javax.swing.JLabel jLabelTolbarTitle;
    private javax.swing.JLabel jLabelTolbarsubTitle;
    private javax.swing.JList<String> jListProjects;
    private javax.swing.JPanel jPainelTolbar;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmptList;
    private javax.swing.JPanel jPanelProjectList;
    private javax.swing.JPanel jPanelProjects;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneProjects;
    private javax.swing.JTable jTableTask;
    // End of variables declaration//GEN-END:variables


public void decorateTableTask(){
    
    //Customizando o header da tabela ou table de tarefas
    jTableTask.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    jTableTask.getTableHeader().setBackground(new Color(0, 204, 102));
    jTableTask.getTableHeader().setForeground(new Color(255, 255, 255));
    //pode ordenar as colunas por ordem alfabetica, por data...
    jTableTask.setAutoCreateRowSorter(true);
    jTableTask.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnRed());
    jTableTask.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRederer("edit"));
    jTableTask.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRederer("delete"));
    

}

public void initDataControler(){
    
    projectControler = new ProjetoControler();
    tarefaControler = new TarefaControler();
}

public void initComponetsModel(){
    
    projectModel = new DefaultListModel();
    loadProjects();
    tarefaModel = new TarefaTableModel();
    jTableTask.setModel(tarefaModel);
   
// loadTasks(2);

    if(!projectModel.isEmpty()){
        jListProjects.setSelectedIndex(0);
        Projeto projeto = (Projeto) projectModel.get(0);
        loadTasks(projeto.getId());
    }
    
    
}

public void loadTasks(int idProjeto){
    List<Tarefa> tarefas = tarefaControler.getAll(idProjeto);
    tarefaModel.setTarefas(tarefas);
    showJTableTarefas(!tarefas.isEmpty());
}

private void showJTableTarefas(boolean hasTarefas){
    //se Existem Tarefas foram carregadas
    if (hasTarefas) {
        if (jPanelEmptList.isVisible()){
            jPanelEmptList.setVisible(false);
            jPanel5.remove(jPanelEmptList);
        }
        jPanel5.add(jScrollPane1);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(jPanel5.getWidth(),jPanel5.getHeight());     
        
    }
    else {
        if (jScrollPane1.isVisible()){
            jScrollPane1.setVisible(false);
            jPanel5.remove(jScrollPane1);
        }
    } jPanel5.add(jPanelEmptList);
      jPanelEmptList.setVisible(true);
      jPanelEmptList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
}

public void loadProjects(){
    
    List<Projeto> projetos = projectControler.getAll();
    
    projectModel.clear();
    
    for (int i = 0; i < projetos.size(); i++) {
        
        Projeto projeto = projetos.get(i);
        projectModel.addElement(projeto);       
    }
    jListProjects.setModel(projectModel);
    
}

}



